baseURL = 'https://lambdacontinuum.github.io/'
languageCode = 'en-us'
title = 'Lambda Continuum'
theme = "ananke"

[outputs]
  home = ['html', 'rss']
  page = ['html', 'rss']
  rss = ['rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[pagination]
pagerSize = 3

[params]
  author = 'Woarna'
  custom_css = ["fonts.css", "button.css"]
  featured_image_class = "cover bg-center"
  favicon = "/images/icon.svg"
  body_classes = "helvetica bg-near-white"
  post_content_classes = "helvetica bg-near-white"
  math = true

[params.ananke.social.follow]
  new_window_icon = false
  networks = [
  "twitter",
  "github",
  "rss"
  ]

[params.ananke.social.twitter]
  username = "woarna_is_right"

[params.ananke.social.github]
  username = "LambdaContinuum"

[params.ananke.social.rss]
  profileLink = "https://lambdacontinuum.github.io/index.xml"

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menus.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menus.main]]
  name = "Substack"
  url = "https://lambdacontinuum.substack.com/"
  weight = 3

[[cascade]]
featured_image = "/images/2.jpg"
[cascade.target]
path = "/posts/**"
kind = "page"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

