baseURL = 'https://lambdacontinuum.github.io/'
languageCode = 'en-us'
title = 'Lambda Continuum'
theme = "hugo-texify3"

[taxonomies]
tags = "tags"
categories = "categories"

[outputs]
  home = ['html', 'rss']
  page = ['html', 'rss']
  rss = ['rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[params]
  title = "Lambda Continuum"
  author = 'Azad Ellafi'
  customCSS = ["css/custom.css"]
  enableDuckDuckGoSearchBox = false

[[menus.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menus.main]]
 name = "Resume"
 url = "/resume.pdf"
 weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params.sharingbuttons]
facebook = false
twitter = false
email = false
linkedin = false
reddit = false
whatsapp = false
hackernews = false
telegram = false

[params.commentEngine]
code = ""

[params.buymeacoffee]
code = ""

